# ─── Model arguments ─────────────────────────────────────────────────────────
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# ─── Data training arguments ─────────────────────────────────────────────────
dataset_name: open-r1/OpenR1-Math-220k
dataset_config: default
dataset_prompt_column: problem
system_prompt:  "You are a helpful AI Assistant that provides well-reasoned and detailed responses. You first think about the reasoning process as an internal monologue and then provide the user with the answer. Respond in the following format: <think>\n...\n</think>\n<answer>\n...\n</answer>"


# ─── SFT trainer config ──────────────────────────────────────────────────────
bf16: true
use_vllm: true
do_eval: false
eval_strategy: steps
eval_steps: 250
per_device_eval_batch_size: 8

gradient_accumulation_steps: 4   # → match GRPO’s new setting
per_device_train_batch_size: 4   # effective batch = 32
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

learning_rate: 5e-6             # matched to your updated GRPO rate
lr_scheduler_type: cosine
warmup_ratio: 0.05              # match your GRPO warmup_ratio

num_train_epochs: 10
max_steps: -1

log_completions: true
log_level: info
logging_first_step: true
logging_strategy: steps
logging_steps: 1

save_strategy: steps
save_steps: 50
save_total_limit: 100

hub_model_id: Qwen2.5-1.5B-Instruct-SFT
hub_strategy: every_save
push_to_hub: true
output_dir: data/Qwen2.5-1.5B-Instruct-SFT-v2
overwrite_output_dir: true

seed: 42
report_to:
  - wandb